<%@ page import="computehash.Hash" %>
<%--
  Created by IntelliJ IDEA.
  User: Animish
  Date: 1/29/2020
  Time: 12:45 AM
  To change this template use File | Settings | File Templates.
--%>
<%--
MVC concept and some code logics referred (not copied) from https://www.baeldung.com/mvc-servlet-jsp
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%= (request.getAttribute("doctype") == null) ? "" : request.getAttribute("doctype") %>
<html>
  <head>
    <title>Hash Functions | Animish Andraskar | DS Project1Task1</title>
  </head>
  <body>
  <% if (request.getAttribute("computedHash") != null) {
    /*** If hash is generated by controller, display it ***/
    Hash hash = (Hash) request.getAttribute("computedHash");
  %>
  <h1>Calculated hash value</h1>
  <div style="margin-bottom: 75px;">
    <table>
      <tr>
        <td>
          <strong>Original text:</strong>
        </td>
        <td>
          <%= hash.originalText %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Hash function:</strong>
        </td>
        <td>
          <%= hash.hashFunction %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Hex hash value:</strong>
        </td>
        <td>
          <%= hash.hexHashValue %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Base64 hash value:</strong>
        </td>
        <td>
          <%= hash.base64HashValue %>
        </td>
      </tr>
    </table>
  </div>

  <% } %>

  <h1>Calculate hash value</h1>

  <% if (request.getAttribute("error") != null && (boolean) request.getAttribute("error")) {
    /*** If any error is sent from the controller ***/
      String errorText = (String) request.getAttribute("errorText");
  %>
  <div style="color: #ff0000;">
    <strong>Error:</strong> <%= errorText %>
  </div><br/>
  <% } %>
  <form method="post" action="/compute_hashes">
    <table>
      <tr>
        <td style="width:210px;">
          <strong>
            Enter text to be hashed:
          </strong>
        </td>
        <td style="width:150px;">
          <input type="text" name="textToHash">
        </td>
      </tr>
      <tr>
        <td>
          <strong>
            Choose hash function:
          </strong>
        </td>
        <td>
          <input type="radio" name="hashFunction" value="md5" checked> MD5<br/>
          <input type="radio" name="hashFunction" value="sha-256"> SHA-256
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div style="text-align: center;">
            <input type="submit" value="Submit">
          </div>
        </td>
      </tr>
    </table>
  </form>
  </body>
</html>
